### ISSUE TITLE
Background Image of person typing on their computer inside the Search country card

### ISSUE THREAD

**Issue by Dj-Viking** [Dj-Viking/Nomadica#32]
# Description
- find a picture to place inside the background of the search country card
- also for country info card, can have an image relating to a country side photo
- I am open to gif images of maybe something like the matrix 

## Notes
- the image has to be more opaque and less contrast as to not blend too much with the other elements

**Comment by junioresc** [comment]
I found a better picture that is of people in a coffee shop on their computers and I placed it next to the search bar, I moved those elements a little to the left.  I also added a white segment before the results that contain the search section. It contrasted better than having a picture inside a picture but the original picture is still shown just later. I also changed the hero url to the local image. Let me know what you think

![nomad-wd-2 0](https://user-images.githubusercontent.com/53980378/87865020-96e50180-c93d-11ea-8858-9440c6b7b728.PNG)

**Comment by Dj-Viking** [comment]
Yeah this is awesome! very sleek and simple. go ahead and commit it, push the branch up and do a pull request! :)

**Comment by junioresc** [comment]
I also just did some media queries so the website looks good no matter what screen size. I also got rid of the weird margins on the page
* Phones
![mobile-friendly-version](https://user-images.githubusercontent.com/53980378/87866007-ffd27680-c949-11ea-94c8-21e456591518.PNG)
* Tablet
![tablet-version](https://user-images.githubusercontent.com/53980378/87866013-082ab180-c94a-11ea-9833-2d56f6b90399.PNG)

**Comment by Dj-Viking** [comment]
Awesome work!
