### ISSUE TITLE
Display searched country flag and/or currency image

### ISSUE THREAD

**Issue by Dannymont94** [Dj-Viking/Nomadica#4]
* Find image API that allows you to search by country
* Fetch at endpoint with country code/country name
* Display image to page

**Comment by Dj-Viking** [comment]
heres the format for a simple API fetch, that can be set to the src attribute of a <img/> tag:
`
img src="https://www.countryflags.io/${countryCode}/shiny/64.png"

**Comment by Dj-Viking** [comment]
Waiting for the HTML to be done before we can display the api fetched info to the DOM

**Comment by Dj-Viking** [comment]
HTML is done and ready to have the DOM portion implemented, this is the last step to this issue before closing

**Comment by Dj-Viking** [comment]
all good
