### ISSUE TITLE
Convey to user how far their money will go in another country

### ISSUE THREAD

**Issue by Dannymont94** [Dj-Viking/Nomadica#5]
* Find currency conversion API
* Feed median salary into converter and convert to searched country's currency
* Display to page

**Comment by Dj-Viking** [comment]
heres a free simple api to use for the conversion rates just change the base query and the symbols query. This will show the current conversion rate for every 1 of the base currency will show how much it yields the symbols currency inside the JSON returned from the promise:

https://api.ratesapi.io/api/latest?base=USD&symbols=GBP

**Comment by Dannymont94** [comment]
This value is now stored in variable convertedSalary within getMedianSalary. Just need to display to page.

**Comment by Dj-Viking** [comment]
waiting for the HTML to be done to start appending the data to the page

**Comment by Dj-Viking** [comment]
HTML is done and now the DOM portion will complete this issue.

**Comment by Dj-Viking** [comment]
make the flag buttons, convert the currency from searched currency code to the target currency within the button
