### ISSUE TITLE
Display median income/poverty line in searched country and compare to web developer median salary

### ISSUE THREAD

**Issue by Dannymont94** [Dj-Viking/Nomadica#6]
* Find API with median incomes/poverty line data per country
* Feed searched country into API
* Display so that users can make comparisons

**Comment by Dj-Viking** [comment]
Still need the HTML to display this data on the page accordingly

**Comment by Dj-Viking** [comment]
HTML is done and now the DOM portion implementation will finish off this issue.

**Comment by Dj-Viking** [comment]
all good
